global:
  scrape_interval: 5s 
  
  external_labels:
    monitor: 'codelab-monitor'
 
scrape_configs:  
  - job_name: 'prometheus'
    scrape_interval: 5s
 
    static_configs:
      - targets: ['localhost:80']

alerting: 
  alertmanagers: 
    - scheme: http
      static_configs:
        # - targets: [ 'alertmanager:9093' ]
        - targets: ['localhost:9093']