global:
  scrape_interval: 20s 
  scrape_timeout: 10s
  
  external_labels:
    monitor: 'codelab-monitor'

rule_files:
  - 'alert.rules'
 
scrape_configs:  
  - job_name: 'prometheus'
    static_configs:
      - targets: ['nginx_exporter:9113']

alerting: 
  alertmanagers: 
    - scheme: http
      static_configs:
        - targets:
          - "alertmanager:9093"